# Generated by Django 5.2.1 on 2025-06-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_category_listing_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listings_won',
            field=models.ManyToManyField(blank=True, related_name='user_winner', to='auctions.listing'),
        ),
    ]
