# Generated by Django 5.2.1 on 2025-06-11 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_winner_bid_alter_bid_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='listings_won',
        ),
        migrations.AddField(
            model_name='listing',
            name='winner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings_won', to=settings.AUTH_USER_MODEL),
        ),
    ]
